### ISSUE TITLE
Missing "Info.plist", "Manifest.plist", "Status.plist"

### ISSUE THREAD

**Issue by jpaxer** [PeterUpfold/dump-iphone-backup#1]
The decrypted backup doesn't contain "Info.plist", "Manifest.plist" or "Status.plist". Because of this, finder doesn't recognize it as a valid backup. I have tried on multiple backups, multiple times. I appreciate any help on this. Thanks!

**Comment by jpaxer** [comment]
From manual testing, I have found that it's as simple as copying the files over, since they aren't encrypted unlike the rest of the backup.

**Comment by PeterUpfold** [comment]
Hi @jpaxer. I'm glad you got this sorted out for your use case.

`dump-iphone-backup` isn't designed to facilitate having the Finder or iTunes recognise a device backup and be able to work with it for restoring etc. This tool is more focused on getting the content _out_ of that format, and into files on your filesystem that you can inspect.

`mvt-ios`'s `decrypt-backup` sub-command may be more useful for your use case! https://docs.mvt.re/en/latest/ios/backup/check/
